<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Case Note Tracking Report</title>
    <style>
        body {
            font-family: 'Helvetica', Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #2c5aa0;
            padding-bottom: 20px;
        }

        .header h1 {
            font-size: 24px;
            font-weight: bold;
            color: #2c5aa0;
            margin: 0 0 10px 0;
        }

        .header h2 {
            font-size: 18px;
            font-weight: normal;
            color: #666;
            margin: 0 0 15px 0;
        }

        .header-info {
            display: flex;
            justify-content: space-between;
            font-size: 11px;
            color: #555;
        }

        .header-info div {
            text-align: left;
        }

        .table-container {
            margin-bottom: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #2c5aa0;
            color: white;
            font-weight: bold;
            padding: 12px 8px;
            text-align: left;
            border: 1px solid #1a3d73;
            font-size: 11px;
        }

        td {
            padding: 10px 8px;
            border: 1px solid #ddd;
            font-size: 11px;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        tr:nth-child(odd) {
            background-color: white;
        }

        .no-column {
            width: 5%;
            text-align: center;
        }

        .date-column {
            width: 12%;
        }

        .request-column {
            width: 15%;
        }

        .patient-column {
            width: 25%;
        }

        .mrn-column {
            width: 12%;
        }

        .user-column {
            width: 20%;
        }

        .summary {
            margin-top: 20px;
            padding: 15px;
            background-color: #f8f9fa;
            border-left: 4px solid #2c5aa0;
        }

        .summary h3 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #2c5aa0;
        }

        .summary p {
            margin: 5px 0;
            font-size: 11px;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 50px;
            background-color: #f8f9fa;
            border-top: 1px solid #ddd;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 20px;
            font-size: 10px;
            color: #666;
        }

        .page-number {
            font-weight: bold;
        }

        .confidential {
            font-style: italic;
        }

        @page {
            margin: 2cm 1.5cm 3cm 1.5cm;
        }

        .page-break {
            page-break-before: always;
        }

        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <h1>Case Note Tracking Report</h1>
        <h2>{{ $caseType === 'in' ? 'Case Note In (Returns)' : 'Case Note Out (Requests)' }}</h2>
        <div class="header-info">
            <div>
                <strong>Date Range:</strong> {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} → {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}
            </div>
            <div>
                <strong>Generated by:</strong> {{ $generatedBy }}<br>
                <strong>Generated on:</strong> {{ $generatedDate }} at {{ $generatedTime }}
            </div>
        </div>
    </div>

    <!-- Table Section -->
    <div class="table-container">
        @if($caseNotes && count($caseNotes) > 0)
            <table>
                <thead>
                    <tr>
                        <th class="no-column">No.</th>
                        <th class="date-column">Date</th>
                        <th class="request-column">Request Number</th>
                        <th class="patient-column">Patient Name</th>
                        <th class="mrn-column">MRN</th>
                        <th class="user-column">{{ $caseType === 'in' ? 'Returned By' : 'Requested By' }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($caseNotes as $index => $caseNote)
                        <tr>
                            <td class="no-column">{{ $index + 1 }}</td>
                            <td class="date-column">{{ \Carbon\Carbon::parse($caseNote['requested_at'])->format('M d, Y') }}</td>
                            <td class="request-column">{{ $caseNote['request_number'] }}</td>
                            <td class="patient-column">{{ $caseNote['patient_name'] }}</td>
                            <td class="mrn-column">{{ $caseNote['mrn'] }}</td>
                            <td class="user-column">{{ $caseNote['requested_by'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <!-- Summary Section -->
            <div class="summary">
                <h3>Report Summary</h3>
                <p><strong>Total {{ $caseType === 'in' ? 'Returns' : 'Requests' }}:</strong> {{ count($caseNotes) }}</p>
                <p><strong>Date Range:</strong> {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</p>
                <p><strong>Report Type:</strong> {{ $caseType === 'in' ? 'Case Note In (Returns)' : 'Case Note Out (Requests)' }}</p>
                <p><strong>Generated:</strong> {{ $generatedDate }} at {{ $generatedTime }}</p>
            </div>
        @else
            <div class="no-data">
                <h3>No Data Found</h3>
                <p>No {{ $caseType === 'in' ? 'returns' : 'requests' }} found for the selected criteria.</p>
                <p>Date Range: {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</p>
            </div>
        @endif
    </div>

    <!-- Footer -->
    <div class="footer">
        <div class="confidential">Confidential – For Medical Record Department Use Only</div>
        <div class="page-number">Page <span class="page-number"></span></div>
    </div>
</body>
</html>
