<?php

/**
 * Production Build Script for CNRS (PHP Version)
 *
 * This script:
 * 1. Builds the frontend with Vite
 * 2. Automatically updates the Blade template with correct asset paths
 * 3. Clears Laravel caches
 * 4. Provides production-ready deployment
 */

echo "🚀 Starting CNRS Production Build Process...\n\n";

// Step 1: Build frontend
echo "📦 Building frontend with Vite...\n";
$buildCommand = 'cd frontend && npm run build 2>&1';
$buildOutput = shell_exec($buildCommand);

if (strpos($buildOutput, 'built in') === false) {
    echo "❌ Frontend build failed:\n";
    echo $buildOutput . "\n";
    exit(1);
}

echo "✅ Frontend build completed successfully\n\n";

// Step 2: Read the generated manifest
echo "📋 Reading manifest for asset paths...\n";
$manifestPath = __DIR__ . '/public/frontend/.vite/manifest.json';

if (!file_exists($manifestPath)) {
    echo "❌ Manifest file not found at: $manifestPath\n";
    exit(1);
}

$manifest = json_decode(file_get_contents($manifestPath), true);
$indexEntry = $manifest['index.html'] ?? null;

if (!$indexEntry) {
    echo "❌ Index entry not found in manifest\n";
    exit(1);
}

$jsFile = $indexEntry['file'] ?? '';
$cssFiles = $indexEntry['css'] ?? [];

echo "📄 JavaScript file: " . basename($jsFile) . "\n";
echo "🎨 CSS files: " . implode(', ', array_map('basename', $cssFiles)) . "\n";

// Step 3: Update Blade template
echo "🔧 Updating Blade template with new asset paths...\n";
$bladeTemplatePath = __DIR__ . '/resources/views/app.blade.php';

if (!file_exists($bladeTemplatePath)) {
    echo "❌ Blade template not found at: $bladeTemplatePath\n";
    exit(1);
}

$bladeContent = file_get_contents($bladeTemplatePath);

// Generate the asset tags (remove 'assets/' prefix from manifest file names)
$baseUrl = '/CNRS/public/frontend/assets/';
$jsFileName = basename($jsFile);
$jsTag = "<script type=\"module\" crossorigin src=\"$baseUrl$jsFileName\"></script>";
$cssTags = '';
foreach ($cssFiles as $css) {
    $cssFileName = basename($css);
    $cssTags .= "<link rel=\"stylesheet\" crossorigin href=\"$baseUrl$cssFileName\">\n";
}

// Find and replace the asset section
$assetSectionRegex = '/(<!-- Vite Assets - Force production mode for network deployment -->[\s\S]*?<\/head>)/';

if (!preg_match($assetSectionRegex, $bladeContent)) {
    echo "❌ Could not find asset section in Blade template to replace\n";
    exit(1);
}

$newAssetSection = "<!-- Vite Assets - Force production mode for network deployment -->\n<!-- Auto-generated by build script - DO NOT EDIT MANUALLY -->\n$jsTag\n$cssTags</head>";

$bladeContent = preg_replace($assetSectionRegex, $newAssetSection, $bladeContent);

// Write updated template
file_put_contents($bladeTemplatePath, $bladeContent);
echo "✅ Blade template updated successfully\n";

// Step 4: Clear Laravel caches
echo "🧹 Clearing Laravel caches...\n";
$cacheCommands = [
    'php artisan view:clear',
    'php artisan cache:clear',
    'php artisan route:clear'
];

foreach ($cacheCommands as $command) {
    $output = shell_exec($command . ' 2>&1');
    if (strpos($output, 'cleared successfully') > 0 || strpos($output, 'INFO') === 0) {
        echo "✅ $command\n";
    } else {
        echo "⚠️ $command - Check manually\n";
    }
}

// Step 5: Final summary
echo "\n🎉 Production build completed successfully!\n";
echo "\n📋 Build Summary:\n";
echo "📦 Frontend built: frontend/dist/\n";
echo "📄 JS Asset: $jsFileName\n";
echo "🎨 CSS Assets: " . implode(', ', array_map('basename', $cssFiles)) . "\n";
echo "🔧 Blade template updated: resources/views/app.blade.php\n";
echo "\n🚀 Your CNRS application is ready for production!\n";
echo "💡 Visit: http://10.2.10.178/CNRS/public/login\n";
echo "\n💡 For future builds, just run:\n";
echo "   php build-production.php\n";
