#!/bin/bash

# CNRS Production Build Script (Bash Version)
#
# This script:
# 1. Builds the frontend with Vite
# 2. Automatically updates the Blade template with correct asset paths
# 3. Clears Laravel caches
# 4. Provides production-ready deployment

echo "🚀 Starting CNRS Production Build Process..."
echo

# Step 1: Build frontend
echo "📦 Building frontend with Vite..."
if cd frontend && npm run build; then
    echo "✅ Frontend build completed successfully"
    cd ..
else
    echo "❌ Frontend build failed"
    exit 1
fi

echo

# Step 2: Update Blade template automatically
echo "🔧 Updating Blade template with new asset paths..."

# Read the JavaScript file from manifest
JS_FILE=$(grep -o '"file": "[^"]*\.js"' public/frontend/.vite/manifest.json | cut -d'"' -f4)

# Read CSS files from manifest
CSS_FILES=$(grep -o '"assets/[^"]*\.css"' public/frontend/.vite/manifest.json | sed 's/"//g')

echo "📄 JavaScript file: $JS_FILE"

# Generate asset tags
BASE_URL="/CNRS/public/frontend/assets/"
JS_TAG="<script type=\"module\" crossorigin src=\"$BASE_URL$JS_FILE\"></script>"

# Create CSS tags
CSS_TAGS=""
for css in $CSS_FILES; do
    CSS_TAGS="$CSS_TAGS
<link rel=\"stylesheet\" crossorigin href=\"$BASE_URL$css\">"
done

# Update Blade template
cp resources/views/app.blade.php resources/views/app.blade.php.backup

# Replace the asset section
awk -v js_tag="$JS_TAG" -v css_tags="$CSS_TAGS" '
/<!-- Vite Assets - Force production mode for network deployment -->/ {
    in_asset_section = 1
    print "<!-- Vite Assets - Force production mode for network deployment -->"
    print "<!-- Auto-generated by build script - DO NOT EDIT MANUALLY -->"
    print js_tag
    print css_tags
    next
}
in_asset_section && /<\/head>/ {
    print "" substr($0, 1, 7)
    in_asset_section = 0
    next
}
in_asset_section { next }
{ print }
' resources/views/app.blade.php.backup > resources/views/app.blade.php

echo "✅ Blade template updated successfully"

# Step 3: Clear Laravel caches
echo "🧹 Clearing Laravel caches..."
php artisan view:clear
php artisan cache:clear
php artisan route:clear
echo "✅ Laravel caches cleared successfully"

echo
echo "🎉 Production build completed successfully!"
echo
echo "📋 Build Summary:"
echo "📦 Frontend built: frontend/dist/"
echo "📄 JS Asset: $JS_FILE"
echo "🎨 CSS Assets: $(echo $CSS_FILES | tr ' ' ',')"
echo "🔧 Blade template updated: resources/views/app.blade.php"
echo
echo "🚀 Your CNRS application is ready for production!"
echo "💡 Visit: http://10.2.10.178/CNRS/public/login"
echo
echo "💡 For future builds, just run:"
echo "   ./build.sh"
